accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name = 'hello_world' ),
    path('create/', AccountCreateView.as_view(), name = 'create'),

    path('login/',LoginView.as_view(template_name='accountapp/login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

]


pragmatic2022/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls'))
]

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)


accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.shortcuts import render
HttpRequest
# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView

from accountapp.models import HelloWorld


def hello_world(request):

    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        hello_world_list = HelloWorld.objects.all()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world') #이거때문에 회원가입하고 나중에 hello_world 페이지로 돌아옴

    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
        <form action="{% url 'accountapp:create' %}" method = "post">
            {% csrf_token %}
{#            {{ form }}#}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <div style="text-align: center; max-width:500px; margin: 4rem auto;">
            <p>
                {{ target_user.date_joined }}
            </p>
            <h2>
                {{ target_user.username }}
            </h2>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="height: 10rem; border-radius: 1rem; margin:2rem; ">
        <h1 style="font-family: 'Nanum Pen Script', cursive;">
            Hello World List
        </h1>

        <form action="/account/hello_world/" method="POST">
            {% csrf_token %}
            <div>
                <input type="text" name = "hello_world_input">
            </div>
            <div>
                <input type="submit" class = "btn btn-primary" vlaue = "POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
                <h4>
                    {{ hello_world.text }}
                </h4>
            {% endfor %}

        {% endif %}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{%  block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;" >
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action = "" method = "post">
                {% csrf_token %}
{#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class ="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>


{%  endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body>

    {% include 'header.html' %}

    {% block content %}

    {% endblock %}

    {% include 'footer.html' %}

</body>


</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class = "pragmatic_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {#부트스트랩#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {#google fonts#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">

    {# DEFAULT CSS LINK #}
    <link rel="stylesheet" type = "text/css" href="{% static 'base.css' %}">


</head>

templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 class = "pragmatic_logo" > Pragmatic</h1>
    </div>

    <div >
        <span>nav1</span>
        <span>nav2</span>
        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }} ">
                <span>login</span>
            </a>
        {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}  ">
                <span>Mypage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }} ">
                <span>logout</span>
            </a>
        {% endif %}
    </div>

</div>